# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/1012/final_project/lab8/lab8.srcs/sources_1/ip/inst_rom/inst_rom.xci
# IP: The module: 'inst_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/1012/final_project/lab8/lab8.gen/sources_1/ip/inst_rom/inst_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/1012/final_project/lab8/lab8.srcs/sources_1/ip/inst_rom/inst_rom.xci
# IP: The module: 'inst_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/1012/final_project/lab8/lab8.gen/sources_1/ip/inst_rom/inst_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
