# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/1012/final_project/lab7/lab7.srcs/sources_1/ip/data_ram_1/data_ram.xci
# IP: The module: 'data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/1012/final_project/lab7/lab7.gen/sources_1/ip/data_ram_1/data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_ram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/1012/final_project/lab7/lab7.srcs/sources_1/ip/data_ram_1/data_ram.xci
# IP: The module: 'data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/1012/final_project/lab7/lab7.gen/sources_1/ip/data_ram_1/data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
